### ISSUE TITLE
Fix security issue of request package 

### ISSUE THREAD

**Issue by klouvas** [honeybadger-io/honeybadger-node#103]
├───────────────┬────────────────────────────────────────┐
 │ Moderate                                       │ An issue was discovered in ajv.validate() in Ajv (aka                                                              │
 │                                                        │ Another JSON Schema Validator) 6.12.2. A carefully crafted                                                │
 │                                                        │  JSON schema could be provided that allows execution of other                                         │
 │                                                        │ code by prototype pollution. (While untrusted schemas are                                                 │
 │                                                        │ recommended against, the worst case of an untrusted schema                                           │
 │                                                        │ should be a denial of service, not execution of code.)                                                           │
├───────────────┼──────────────────────────────────────── ┤
 │ Package                                         │ ajv                                                                                                                                                │
├───────────────┼──────────────────────────────────────── ┤
 │ Patched in                                     │ 6.12.3                                                                                                                                           │
├───────────────┼──────────────────────────────────────── ┤
 │ Dependency of                             │ honeybadger                                                                                                                               │
├───────────────┼──────────────────────────────────────── ┤
 │ Path                                                │ honeybadger > request > har-validator > ajv                                                                          │
├───────────────┼────────────────────────────────────────  ┤
 │ More info                                        │ https://github.com/ajv-validator/ajv/releases/tag/v6.12.3                                                │
└───────────────┴────────────────────────────────────────┘

**Comment by joshuap** [comment]
Thanks! I'll get this fixed today.

**Comment by joshuap** [comment]
It looks like the fix for this is waiting upstream. I'll update the depedency as soon as there is a new release:

https://github.com/request/request/issues/3330
https://github.com/request/request/pull/3332

**Comment by klouvas** [comment]
Thanks!

**Comment by klouvas** [comment]
i will close this
