### ISSUE TITLE
Update `request` package

### ISSUE THREAD

**Issue by nshoes** [honeybadger-io/honeybadger-node#20]
[`request`](https://github.com/request/request) used to use the `node-uuid` package and it is giving me annoying errors:

<img width="508" alt="screen shot 2017-02-15 at 9 01 00 am" src="https://cloud.githubusercontent.com/assets/4118389/22985703/10306ffc-f35e-11e6-8c96-b66265425ece.png">

Please upgrade `request` to it's latest version (`2.79.1`) if possible; they are [now using the proper`uuid` package](https://github.com/request/request/blob/master/package.json#L49).

**Comment by joshuap** [comment]
@nshoes released in 1.2.1
