### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by Yuvarajsap** [honeybadger-io/honeybadger-node#21]
{
	"preview": false,
	"result": {
		"job": "test-job",
		"Status": "SUCCESS",
		"_time": "2018-01-22T11:10:45.000+0000",
		"source": "/opt/CA/WorkloadAutomationAE/autouser.PRD/out/event_demon.PRD",
		"host": "abc.abcnjh.com",
		"machine": "abcnjh.com",
		"event": "CHANGE_STATUS",
		"exitcodestatus": "0"
	}
}

Wanted to know the exact code for extracting the above log message in nodejs.

I am using the below command, but I am getting undefined error.

exports.handler = (event, context, callback) => {
    // TODO implement
    console.log("preview  "+event.preview);
    console.log("results  "+event.result);
    console.log("job = " +event.job);
    console.log("Status  "+context.Status);
     /*console.log("Job_Name  "+event.job);
    console.log("Status  "+event.Status);
     console.log("_time  "+event._time);
     console.log("source = " + event.source); 
   console.log("toolInstance = " + event.toolInstance); */
    callback(null, 'Hello from Lambda');
};

**Comment by joshuap** [comment]
Hi @Yuvarajsap, I'm not quite sure how this relates to honeybadger-node. Do you mean you're getting an error in our library? If so, could you attach the error message and stack trace?
