### ISSUE TITLE
Vulnerability issue relating to hoek@2.16.3

### ISSUE THREAD

**Issue by azzamallow** [honeybadger-io/honeybadger-node#22]
Github informed us of a vulnerability relating to `hoek@2.16.3`, which when I trace our dependancies leads us to the honeybadger package.

![screen shot 2018-05-02 at 11 18 42 am](https://user-images.githubusercontent.com/164221/39500823-9fc772a8-4dfa-11e8-9baa-cd0ae27835f1.png)

From that tree structure it relates to `request@2.79.0` dependancy you have in your package.json.

There is an open issue form the `request` package, see: https://github.com/request/request/issues/2926

I'm not sure you can do anything until that issue is resolved, but I wanted to put it on your radar.

**Comment by stympy** [comment]
Thanks for the heads-up!

**Comment by stympy** [comment]
This was a false flag (see https://github.com/hapijs/hoek/issues/247#issuecomment-386708295), so I'm closing.
