### ISSUE TITLE
Support async functions in lambdaHandler

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-node#54]
We've had one report that async support may not fully work with `Honeybadger.lambdaHandler`. See examples here: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html

**Comment by DanNeish** [comment]
@joshuap, I have tried using Honeybadger.lambdaHandler with an async lambda function and it does not work. It would be great if we could get this working.

**Comment by joshuap** [comment]
As of [honeybadger 1.4.0](https://www.npmjs.com/package/honeybadger/v/1.4.0), the new `Honeybadger.lambdaHandler` works with async and non-async functions!
