### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by mikew** [honeybadger-io/honeybadger-node#94]
Do sourcemaps work with honeybadger-node? Looking through [your documentation](https://docs.honeybadger.io/lib/javascript/guides/using-source-maps.html), it seems that:

1. you must have a single `.js` file
1. you must have a single `.js.map` file
1. your `.js` file must be accessible over the internet

The first two aren't the case when not using webpack, and the latter isn't applicable to servers.

**Comment by joshuap** [comment]
No, we don't currently support source maps for node. Our [browser](https://github.com/honeybadger-io/honeybadger-js) and [node](https://github.com/honeybadger-io/honeybadger-node) packages are currently separate independent projects. Right now we only support source maps for browsers. I'm currently working on a new universal JavaScript package which will eventually replace both projects. I don't have plans to support server-side source maps in that package yet, but it might be an option. I'll make a note to look into it!
